#!/bin/bash
#n1 -eq n2 Возвращает истинное значение, если n1 равно n2.
#n1 -ge n2 Возвращает истинное значение, если n1 больше или равно #n2.
#n1 -gt n2 Возвращает истинное значение, если n1 больше n2.
#n1 -le n2 Возвращает истинное значение, если n1 меньше или равно #n2.
#n1 -lt n2 Возвращает истинное значение, если n1 меньше n2.
#n1 -ne n2 Возвращает истинное значение, если n1 не равно n2
val1=6
if [ $val1 -gt 5 ]
then
echo "The test value $value1 is greater than 5"
else
echo "The test value $value1 is not greater than 5"
fi


